datasets:
    LibriSpeech:
        root: ./data/LibriSpeech
        trainsets: ['dev', 'test','train']
        testsets: ['test-clean']
view:
    train_filelist: ./data/librispeech_train.tsv
    test_filelist: ./data/librispeech_test.tsv
audio:
  sr: 16000
  normalization: False
  max_wav_value: 32768.0
stft:
  n_fft: 1280
  window_length: 1280
  hop_length: 320
