dataset:
  _target_: data_module.StandardAudioDataset
  name: librispeech  # Name of the processed dataset
  root: ./data  # Root directory containing processed datasets

train:
  batch_size: 8
  shuffle: true

val:
  batch_size: 8
  shuffle: false

test:
  batch_size: 1
  shuffle: false

padding_idx: 0
frame_length: 200
min_audio_length: 96000
