dataset:
  _target_: data_module.FSDataset_add_STFT

train:
  filelist: ./data/librispeech_train.tsv
  batch_size: 8
  shuffle: true

val:
  filelist: ./data/librispeech_dev.tsv
  batch_size:  8
  shuffle: false

test:
  filelist: ./data/librispeech_test.tsv
  batch_size: 1
  shuffle: false
padding_idx: 0
frame_length: 200
min_audio_length: 96000
